Peli.MVC/Models/ErrorViewModel.cs
using System;

namespace Peli.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Peli.MVC/ViewModels/VMPelicula.cs
using Peli.Core;
using System.Collections.Generic;

namespace Peli.MVC.ViewModels
{
    public class VMPelicula
    {
        public IEnumerable<Genero> Generos { get; set; }

        public IEnumerable<Productora> Productoras{get;set;}

        public Pelicula Pelicula { get; set; }

        public int? IdGeneroSeleccionado { get; set; }

        public int? IdProductoraSeleccionada {get;set;}
        
        public VMPelicula() => Pelicula = new Pelicula();
        
        public VMPelicula(IEnumerable<Genero> generos) : this()
            => Generos = generos;

        public VMPelicula(IEnumerable<Genero> generos, IEnumerable<Productora> productoras) : this(generos)
            => Productoras = productoras;
    }
}

Peli.MVC/Controllers/GeneroController.cs
using Microsoft.AspNetCore.Mvc;
using Peli.Core;

namespace Peli.Controllers
{
    public class GeneroController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        => View(Repositorio.Generos);

        [HttpGet]
        public IActionResult Detalle(int id)
        {
            var genero = Repositorio.GetGenero(id);
            if (genero is null)
            {
                return NotFound();
            }
            return View(genero);
        }
        [HttpGet]

        public IActionResult FormAlta() => View();

        [HttpPost]

        public IActionResult FormAlta(Genero genero)
        {
            Repositorio.AgregarGenero(genero);
            return View("index", Repositorio.Generos);
        }

    }
}

Peli.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Peli.MVC.Models;

namespace Peli.MVC.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult index()
        {
            return View();
        }
    }}

Peli.MVC/Controllers/PeliculaController.cs
using Microsoft.AspNetCore.Mvc;
using Peli.Core;
using Peli.MVC.ViewModels;

namespace Peli.Controllers
{
    public class PeliculaController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        => View(Repositorio.Peliculas);

        [HttpGet]
        public IActionResult Detalle(int id)
        {
            var pelicula = Repositorio.GetPelicula(id);
            if (pelicula is null)
            {
                return NotFound();
            }
            return View(pelicula);
        }
        [HttpGet]

        public IActionResult FormAlta(int? idGenero , int? idProductora)
         {
            var vmPelicula= new VMPelicula(Repositorio.Generos, Repositorio.Productoras )
            {
               IdGeneroSeleccionado = idGenero,
               IdProductoraSeleccionada = idProductora
            };
            return View(vmPelicula);
        }


        [HttpPost]

        public IActionResult FormAlta(VMPelicula vMPelicula)
        {
             var genero = Repositorio.GetGenero(vMPelicula.IdGeneroSeleccionado.Value);
             var prductora = Repositorio.GetProductora(vMPelicula.IdProductoraSeleccionada.Value);
             vMPelicula.Pelicula.genero = genero;
             vMPelicula.Pelicula.productora=prductora;
             Repositorio.AgregarPelicula(vMPelicula.Pelicula);
             genero.AgregarPelicula(vMPelicula.Pelicula);
            prductora.AgregarPelicula(vMPelicula.Pelicula);
             return View("Index",Repositorio.Peliculas);

             
    }
    
}
}

Peli.MVC/Controllers/ProductoraController.cs
using Microsoft.AspNetCore.Mvc;
using Peli.Core;

namespace Peli.Controllers
{
    public class ProductoraController : Controller
    {
        [HttpGet]
      
      public ActionResult Index()
      => View(Repositorio.Productoras);

[HttpGet]
public IActionResult Detalle(int id)
{
    var productora = Repositorio.GetProductora(id);
    if(productora is null)
    {
        return NotFound();
    }
    return View(productora);
}
[HttpGet]
 public IActionResult FormAlta() => View();

        [HttpPost]

        public IActionResult FormAlta(Productora productora)
        {
            Repositorio.AgregarProductora(productora);
            return View("index", Repositorio.Productoras);
        }
    }
}

Peli.MVC/Views/Genero/Detalle.cshtml
@model Peli.Core.Genero
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Detalle - Genero</title>
</head>

<body>
    <h1>Detalle</h1>
    <h3> Nombre: @Model.Nombre </h3>
    <table>
        <thead>
            <tr>
                <th>Peliculas</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Peli.Core.Pelicula pelicula in Model.Peliculas)
            {
                <tr>
                    <td>@pelicula.Titulo</td>
                </tr>
            }
        </tbody>
    </table>
    <button>
        <a asp-controller="" asp-action="Index"> inicio </a>
    </button>
</body>

</html>

Peli.MVC/Views/Genero/FormAlta.cshtml
@model Peli.Core.Genero
@{
    Layout = "_Layout3";
}
<!DOCTYPE html>
<head>
    <title>Pelicula - Genero</title>
</head>
<body>
    <div class="isolate">
    <div class="second obj">
    <form asp-action="FormAlta" method="post">
        <div asp-validation-summary="All"></div>
        <div class="field is-horizontal ">
            <label class = "la"  asp-for="Nombre">GENEROS:</label>
            <input class="input is-link"  asp-for="Nombre" />
        </div>
        <button class="bu" type="submit">Alta Genero</button>
    </form>
    </div>
    </div>
</body>
</html>

Peli.MVC/Views/Genero/Index.cshtml
@model  IEnumerable<Peli.Core.Genero>
@{
    Layout = "_Layout2";
}
<html>
    <head>
        <title>Pelicula - Genero</title>
    </head>
    <div class="isolate">
    <div class="second obj">
    <body>
<h1 class="c">Generos</h1>
<table class="table is-bordered">
    <thead>
        <tr>
    <th class="g3">Nombre</th>
    </tr>
    </thead>
    <tbody>
    @foreach (Peli.Core.Genero genero in Model)
    {
        <tr>
        <td class="g2">
        <a asp-controller="Genero" asp-action="Detalle" asp-route-id="@genero.Id">@genero.Nombre</a> 
        </td>
        </tr>
    }
    </tbody>
</table>
<br>
  <button class="bu">
<a asp-controller="" asp-action="Index">Inicio</a>
</button>
    </body>
    </div>
    </div>
</html>

Peli.MVC/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<!DOCTYPE html>
<html>

<head>

  <title>Peliculas</title>
</head>
<body>
  <div class="isolate">
  <div class="second obj">
  <h1 class="c">Elige Donde Entrar</h1>
    <table class="table is-bordered" align="center" width ="30%" height = "30%">
      <tr>
        <th class="g3">GENERO</th>
        <th class="g3">PRODUCTORA</th>
        <th class="g3">PELICULA</th>
      </tr>
      <tr class="e">
        <td><a asp-controller="Genero" asp-action="Index">Ver Generos</a></td>
        <td><a asp-controller="Productora" asp-action="Index">Ver Productoras</a></td>
        <td><a asp-controller="Pelicula" asp-action="Index">Ver Peliculas</a></td>

      </tr>
      <tr class="e">
        <td> <a asp-controller="Genero" asp-action="FormAlta">Alta Genero</a></td>
        <td><a asp-controller="Productora" asp-action="FormAlta">Alta Productora</a></td>
        <td><a asp-controller="Pelicula" asp-action="FormAlta">Alta Pelicula</a></td>

      </tr>
    </table>
    </div>
</div>
</body>
</html>

Peli.MVC/Views/Pelicula/Detalle.cshtml
@model Peli.Core.Pelicula
@{
    Layout = "_Layout2";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Detalle - Pelicula</title>
</head>
<body>
    <h1 class="c">Detalle</h1>
    <table class=" table is-bordered">
        <thead>
            <tr>
                <th class="g3">Duracion</th>
                <th class="g3">FechaEstreno</th>
                <th class="g3">Genero</th>
                <th class="g3">Productora</th>
            </tr>
        </thead>
        <tbody>
         <td class="g2">@Model.Duracion</td> 
         <td class="g2">@Model.FechaEstreno</td>
         <td class="g2">@Model.genero.Nombre</td>
         <td class="g2">@Model.productora.Nombre</td>
        </tbody>
    </table>
    <button>
<a  asp-controller="" asp-action="Index">Inicio</a>
</button>
</body>
</html>

Peli.MVC/Views/Pelicula/FormAlta.cshtml
@model Peli.MVC.ViewModels.VMPelicula;
@{
    Layout = "_Layout3";
}
<!DOCTYPE html>
<head>
    <title>Pelicula - Peliculas</title>
</head>
<div class="isolate">
<div class="second obj">

<body>
    <form asp-action="FormAlta" method="post">
        <div asp-validation-summary="All"></div>
        <div class="field is-horizontal ">
            <label class = "la" asp-for="@Model.Pelicula.Titulo">PELICULA</label>
            <input class="input is-link" asp-for="@Model.Pelicula.Titulo" />
        </div>
         <div class="field is-horizontal ">
            <label class = "la" asp-for="@Model.Pelicula.Duracion">DURACION</label>
            <input class="input is-link" asp-for="@Model.Pelicula.Duracion" />
        </div>
         <div class="field is-horizontal ">
            <label class = "la" asp-for="@Model.Pelicula.FechaEstreno">FECHAESTRENO</label>
            <input class="input is-link" asp-for="@Model.Pelicula.FechaEstreno" />
        </div>
     <div class="field is-horizontal ">
            <label class = "la" asp-for="@Model.Pelicula.Descripcion">DESCRIPCION</label>
            <input class="input is-link" asp-for="@Model.Pelicula.Descripcion" />
        </div>
        <div>
            
        <select class="bu" asp-for="IdGeneroSeleccionado">
                <option value="">Elegi Genero</option>
                @foreach (Peli.Core.Genero genero in Model.Generos)
                {
                    <option value="@genero.Id">@genero.Nombre</option>                 
                }
            </select>
            </div>
             <div>
            
        <select class="bu" asp-for="IdProductoraSeleccionada">
                <option value="">Elegi Productora</option>
                @foreach (Peli.Core.Productora productora in Model.Productoras)
                {
                    <option value="@productora.Id">@productora.Nombre</option>                 
                }
            </select>
            </div>
        <button type="submit" class="bu">Alta Pelicula</button>
    </form>
</body>
</div>
</div>
</html>

Peli.MVC/Views/Pelicula/Index.cshtml
@model IEnumerable<Peli.Core.Pelicula>
@{
  Layout = "_Layout2";
}
<html>

<head>
  <title> Peliculas</title>
  </div>
</head>

<body>
  <div class="isolate">
  <div class="second obj">
    <h1 class="c">PELICULAS</h1>
  <table class="table is-bordered">
    <thead>
      <tr>
        <th class="g3">Titulo</th>
        <th class="g3">Descripcion</th>
      </tr>
    </thead>
    <tbody>
      @foreach (Peli.Core.Pelicula pelicula in Model)
      {
        <tr>

          <td class="g2"><a asp-controller="Pelicula" asp-action="Detalle" asp-route-id="@pelicula.Id">@pelicula.Titulo</a> </td>
          <td class="g2"><a asp-controller="Pelicula" asp-action="Detalle" asp-route-id="@pelicula.Id">@pelicula.Descripcion</a></td>
        </tr>
      }
    </tbody>
  </table>
  <br>
  <button class="bu">
<a asp-controller="" asp-action="Index">Inicio</a>
</button>
</div>
</div>
</body>

</html>

Peli.MVC/Views/Productora/Detalle.cshtml
@model Peli.Core.Productora
@{
    Layout =null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Detalle - Pelicula</title>
</head>
<body>
    <h1>Detalle</h1>
    <h3 > Nombre: @Model.Nombre </h3>
    <table>
        <thead>
            <tr>
                <th>Peliculas</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Peli.Core.Pelicula pelicula in Model.Peliculas)
            {
            <tr>
                <td>
   <a asp-controller="Pelicula" asp-action="Detalle" asp-route-id="@pelicula.Id">@pelicula.Titulo</a>

                </td>
            </tr>
            }
        </tbody>
    </table>
    <button>
<a asp-controller="" asp-action="Index"> inicio </a>
</button>
</body>
</html>

Peli.MVC/Views/Productora/FormAlta.cshtml
@model Peli.Core.Productora
@{
    Layout = "_Layout3";
}
<!DOCTYPE html>
<head>
    <title>Pelicula - Productora</title>
</head>
<body>
    <div class="isolate">
<div class="second obj">
    <form asp-action="FormAlta" method="post">
        <div asp-validation-summary="All"></div>
        <div  class="field is-horizontal ">
            <label class = "la" asp-for="Nombre">PRODUCTORA: </label>
            <input class="input is-link" asp-for="Nombre" />
        </div>
        <button class="bu" type="submit">Alta Productora</button>
    </form>
    </div>
</div>
</body>
</html>

Peli.MVC/Views/Productora/Index.cshtml
@model IEnumerable<Peli.Core.Productora>
@{
  Layout = "_Layout2";
}

<html>

<head>
  <title>Productora</title>
</head>
<body>
  <div class="isolate">
  <div class="second obj">
  <h1 class="c">PRODUCTORA</h1>
  <table class="table is-bordered">
    <thead>
      <tr>
        <th class="g3">Nombre</th>
      </tr>
    </thead>
    <tbody>
      @foreach (Peli.Core.Productora productora in Model)
      {
        <tr>
          <td class="g2"><a asp-controller="Productora" asp-action="Detalle"
            asp-route-id="@productora.Id">@productora.Nombre</a> </td>
        </tr>
      }
    </tbody>
  </table>
  <button class="bu">
    <a asp-controller="" asp-action="Index">Inicio</a>
  </button>
  </div>
  </div>
</body>
</html>

Peli.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Peli.MVC</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <header>
    </header>
     <div class="container is-max-desktop"></div>
        @RenderBody()
    </div>
</body>
</html>

Peli.MVC/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Peli.MVC</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <header>

    </header>
     <div class="container is-max-desktop"></div>
        @RenderBody()
    </div>
</body>
</html>

Peli.MVC/Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Peli.MVC</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <header>

    </header>
     <div class="container is-max-desktop"></div>
        @RenderBody()
    </div>
</body>
</html>